sfdx-source/common-base/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/ApplicationFactory_SelectorBinding__mdt.object-meta.xml
<CustomObject>
    <description>All Force-DI bindings for SObject Selectors to the ApplicationSObjectSelectorDIModule</description>
    <label>ApplicationFactory_SelectorBinding</label>
    <pluralLabel>ApplicationFactory_SelectorBindings</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/fields/BindingSObjectAlternate__c.field-meta.xml
<CustomField>
    <fullName>BindingSObjectAlternate__c</fullName>
    <description>Use this field to specify the SObject API name to bind to when the &quot;Binding SObject&quot; field does not list that particular SObject.  Only specify the &quot;Binding SObject&quot; field or this one; not both.</description>
    <inlineHelpText>Use this field to specify the SObject API name to bind to when the &quot;Binding SObject&quot; field does not list that particular SObject.  Only specify the &quot;Binding SObject&quot; field or this one; not both.</inlineHelpText>
    <label>Binding SObject Alternate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>The Selector implementation class that is an implementation of the IApplicationSObjectSelector</description>
    <inlineHelpText>The Selector implementation class that is an implementation of the IApplicationSObjectSelector</inlineHelpText>
    <label>To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/test/classes/framework-application-factory/ApplicationSObjectSelectorTest.cls
@IsTest
private class ApplicationSObjectSelectorTest
{
    @IsTest
    private static void getSObjectFieldListTest()
    {
        configureSelectors();

        TestOnlyClasses.TestAccountsSelector sel = (TestOnlyClasses.TestAccountsSelector) Application.Selector.newInstance(Account.SObjectType);
        List<SObjectField> fieldList = sel.getSObjectFieldList();

        System.assert(fieldList != null);
        System.assertEquals(false, fieldList.isEmpty());
    }

    @IsTest
    private static void selectionInjectionTest()
    {
        configureSelectors();

        TestSelectorMethod.Parameters queryParams = new TestSelectorMethod.Parameters();
        queryParams.accountNumberSet = new Set<String>{ '123456' };

        TestOnlyClasses.TestAccountsSelector sel = (TestOnlyClasses.TestAccountsSelector) Application.Selector.newInstance(Account.SObjectType);
        List<Account> accountList = sel.selectInjection(TestSelectorMethod.class, queryParams);

        System.assert(accountList != null);
        System.assert(accountList.isEmpty());
    }

    private static void configureSelectors()
    {
        ApplicationFactory_SelectorBinding__mdt accountsSelectorBinding = new ApplicationFactory_SelectorBinding__mdt();
        accountsSelectorBinding.BindingSObjectAlternate__c = 'Account';
        accountsSelectorBinding.To__c = 'TestOnlyClasses.TestAccountsSelector';

        ApplicationFactory_SelectorBinding__mdt contactsSelectorBinding = new ApplicationFactory_SelectorBinding__mdt();
        contactsSelectorBinding.BindingSObjectAlternate__c = 'Contact';
        contactsSelectorBinding.To__c = 'TestOnlyClasses.TestContactsSelector';

        List<ApplicationFactory_SelectorBinding__mdt> bindingList = new List<ApplicationFactory_SelectorBinding__mdt>
        {
            accountsSelectorBinding,
            contactsSelectorBinding
        };

        ApplicationSObjectSelectorDIModule.setMock(bindingList);
    }
}