sfdx-source/common-base/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/ApplicationFactory_SelectorBinding__mdt.object-meta.xml
<CustomObject>
    <description>All Force-DI bindings for SObject Selectors to the ApplicationSObjectSelectorDIModule</description>
    <label>ApplicationFactory_SelectorBinding</label>
    <pluralLabel>ApplicationFactory_SelectorBindings</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/fields/BindingSObject__c.field-meta.xml
<CustomField>
    <fullName>BindingSObject__c</fullName>
    <description>The SObject that this Application Factory Selector Binding is mapped to.</description>
    <inlineHelpText>The SObject that this Application Factory Selector Binding is mapped to.</inlineHelpText>
    <label>Binding SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>ApplicationFactory_SelectorBindings</relationshipLabel>
    <relationshipName>ApplicationFactory_SelectorBindings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

sfdx-source/common-base/main/schema/objects/ApplicationFactory_SelectorBinding__mdt/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>The Selector implementation class that is an implementation of the IApplicationSObjectSelector</description>
    <inlineHelpText>The Selector implementation class that is an implementation of the IApplicationSObjectSelector</inlineHelpText>
    <label>To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/common-base/main/classes/framework/ApplicationSObjectServiceDIModule.cls
/**
 *
 * di_Module based class used to manage the Application Factory mappings of for the SOBject
 */
public class ApplicationSObjectServiceDIModule 
    extends di_Module
{
    public override void configure() 
    {
        System.debug('loading the SObjectSelector bindings for Application Factory');
        Schema.DescribeSobjectResult[] results = null;

        for ( ApplicationFactory_SelectorBinding__mdt bindingConfig : [select DeveloperName, QualifiedAPIName, To__c, BindingSObject__c 
                                                                         from ApplicationFactory_SelectorBinding__mdt])
        {
            apex();
            if (String.isNotBlank(bindingConfig.BindingSObject__c)) 
            {
                results = Schema.describeSObjects(new String[] { bindingConfig.BindingSObject__c.toLowerCase().trim() });
                if(results.size() != 1) 
                {
                    throw new di_Injector.InjectorException('Failed to find SObject ' + bindingConfig.BindingSObject__c + ' referened by binding ' + bindingConfig.DeveloperName + ' for ApplicationSObjectSelectorDIModule di_Injectory module.');
                }
                bind(results[0].getSObjectType());
                bind(IApplicationSObjectSelector.class);
            }
            data(bindingConfig);
            to(bindingConfig.To__c);
        }
    }
}