sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/TestDataSupplementer__mdt.object-meta.xml
<CustomObject>
    <description>Defines ITestDataSupplementer classes that add data to SObjects necessary to meet testing requirements.</description>
    <label>Test Data Supplementer</label>
    <pluralLabel>Test Data Supplementers</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/fields/BindingSObjectType__c.field-meta.xml
<CustomField>
    <fullName>BindingSObjectType__c</fullName>
    <description>The SObject Type to which the supplementing class is related.</description>
    <inlineHelpText>The SObject Type to which the supplementing class is related.</inlineHelpText>
    <label>Binding SObject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Test_Data_Supplementers</relationshipLabel>
    <relationshipName>Test_Data_Supplementers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/fields/SupplementingClass__c.field-meta.xml
<CustomField>
    <fullName>SupplementingClass__c</fullName>
    <description>The class implementing the logic to supplement the SObject.</description>
    <inlineHelpText>The class implementing the logic to supplement the SObject.</inlineHelpText>
    <label>SupplementingClass</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/common-base/main/classes/framework/TestDataSupplementer.cls
public class TestDataSupplementer
{
    private Map<SObjectType, List<ITestDataSupplement>> supplementerMap = new Map<SObjectType, List<ITestDataSupplement>>();

    public TestDataSupplementer()
    {
        for (
            di_Binding binding
            :
            di_Injector.Org.Bindings
                .byName(ITestDataSupplement.class.getName())
                .get()
        )
        {
            TestDataSupplementer__mdt tds_mdt = (TestDataSupplementer__mdt) binding.Data;
            SObjectType sobjType = Schema.getGlobalDescribe().get(tds_mdt.BindingSObjectType__c);

            if (sobjType == null)
            {
                System.debug(
                    LoggingLevel.ERROR,
                    'SObjectType, ' + tds_mdt.BindingSObjectType__c + 
                    ', specified in  ' + tds_mdt.DeveloperName + 
                    ' does not exist.'
                );

                continue;
            }

            ITestDataSupplement instance = null;
            if (String.isNotBlank(tds_mdt.SupplementingClass__c))
            {
                Type t = Type.forName(tds_mdt.SupplementingClass__c);

                if (t == null)
                {
                    System.debug(
                        LoggingLevel.ERROR,
                        'Type , ' + tds_mdt.SupplementingClass__c + 
                        ', specified in  ' + tds_mdt.DeveloperName + 
                        ' does not exist.');

                    continue;
                }

                instance = (ITestDataSupplement) t.newInstance();
            }

            if (instance == null)
            {
                System.debug(
                    LoggingLevel.ERROR,
                    'Type , ' + tds_mdt.SupplementingClass__c + 
                    ', specified in  ' + tds_mdt.DeveloperName + 
                    ' could not be created.');

                continue;
            }

            if (!supplementerMap.containsKey(sobjType))
            {
                supplementerMap.put(sobjType, new List<ITestDataSupplement>());
            }

            supplementerMap.get(sobjType).add(instance);

        }

        System.debug(supplementerMap);
    }

    public void supplement (List<SObject> sobjectList)
    {
        if (sobjectList != null && !sobjectList.isEmpty())
        {
            for (ITestDataSupplement supplementer : supplementerMap.get(sobjectList.getSObjectType()))
            {
                supplementer.supplement(sobjectList);
            }
        }
    }
}