sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/TestDataSupplementer__mdt.object-meta.xml
<CustomObject>
    <description>Defines ITestDataSupplementer classes that add data to SObjects necessary to meet testing requirements.</description>
    <label>Test Data Supplementer</label>
    <pluralLabel>Test Data Supplementers</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/fields/BindingSObjectType__c.field-meta.xml
<CustomField>
    <fullName>BindingSObjectType__c</fullName>
    <description>The SObject Type to which the supplementing class is related.</description>
    <inlineHelpText>The SObject Type to which the supplementing class is related.</inlineHelpText>
    <label>Binding SObject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Test_Data_Supplementers</relationshipLabel>
    <relationshipName>Test_Data_Supplementers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/core/main/schema/objects/TestDataSupplementer__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>A value used to ascendingly sort the supplementers to accommodate dependencies.</description>
    <inlineHelpText>A value used to ascendingly sort the supplementers to accommodate dependencies.</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/fields/SupplementingClass__c.field-meta.xml
<CustomField>
    <fullName>SupplementingClass__c</fullName>
    <description>The class implementing the logic to supplement the SObject.</description>
    <inlineHelpText>The class implementing the logic to supplement the SObject.</inlineHelpText>
    <label>SupplementingClass</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/classes/framework-test-data-supplementer/TestDataSupplementDIModule.cls
@IsTest
public class TestDataSupplementDIModule
    extends di_Module
{
    public override void configure()
    {
        Schema.DescribeSobjectResult[] results = null;

        for (TestDataSupplementer__mdt bindingConfig : [select DeveloperName, QualifiedAPIName, BindingSObjectType__c
                                                             , BindingSObjectType__r.QualifiedApiName, SupplementingClass__c 
                                                          from TestDataSupplementer__mdt 
                                                         order by Sequence__c])
        {
            apex();
            if (String.isNotBlank(bindingConfig.BindingSObjectType__c)) 
            {
                results = Schema.describeSObjects(new String[] { bindingConfig.BindingSObjectType__r.QualifiedApiName.toLowerCase().trim() });
                if(results.size() != 1) 
                {
                    throw new di_Injector.InjectorException(
                        'Failed to find SObject ' + bindingConfig.BindingSObjectType__r.QualifiedApiName + 
                        ' referened by binding ' + bindingConfig.DeveloperName + 
                        ' for TestDataSupplementDIModule di_Injection module.');
                }
                bind(results[0].getSObjectType());
                bind(ITestDataSupplement.class);
            }
            data(bindingConfig);
            to(bindingConfig.SupplementingClass__c);
        }
    }
}