sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/TestDataSupplementer__mdt.object-meta.xml
<CustomObject>
    <description>Defines ITestDataSupplementer classes that add data to SObjects necessary to meet testing requirements.</description>
    <label>Test Data Supplementer</label>
    <pluralLabel>Test Data Supplementers</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/TestDataSupplementer__mdt/fields/BindingSObjectType__c.field-meta.xml
<CustomField>
    <fullName>BindingSObjectType__c</fullName>
    <description>The SObject Type to which the supplementing class is related.</description>
    <inlineHelpText>The SObject Type to which the supplementing class is related.</inlineHelpText>
    <label>Binding SObject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Test_Data_Supplementers</relationshipLabel>
    <relationshipName>Test_Data_Supplementers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/core/main/classes/framework-test-data-supplementer/TestDataSupplementer.cls
@IsTest
public class TestDataSupplementer
{
    private static Map<SObjectType, List<ITestDataSupplement>> supplementerMap = new Map<SObjectType, List<ITestDataSupplement>>();

    static
    {
        for (
            di_Binding binding
            :
            di_Injector.Org.Bindings
                .byName(ITestDataSupplement.class.getName())
                .get()
        )
        {
            TestDataSupplementer__mdt tds_mdt = (TestDataSupplementer__mdt) binding.Data;
            SObjectType sobjType = Schema.getGlobalDescribe().get(tds_mdt.BindingSObjectType__c);

            if (!supplementerMap.containsKey(sobjType))
            {
                supplementerMap.put(sobjType, new List<ITestDataSupplement>());
            }

            supplementerMap.get(sobjType).add((ITestDataSupplement) binding.getInstance());
        }
    }

    public static void supplement (List<SObject> sobjectList)
    {
        if (sobjectList != null && !sobjectList.isEmpty())
        {
            for (ITestDataSupplement supplementer : supplementerMap.get(sobjectList.getSObjectType()))
            {
                supplementer.supplement(sobjectList);
            }
        }
    }
}