sfdx-source/common-base/main/schema/objects/ApplicationFactory_DomainBinding__mdt/ApplicationFactory_DomainBinding__mdt.object-meta.xml
<CustomObject>
    <description>All Force-DI bindings for SObject Selectors to the ApplicationSObjectDomainDIModule</description>
    <label>ApplicationFactory_DomainBinding</label>
    <pluralLabel>ApplicationFactory_DomainBindings</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/ApplicationFactory_DomainBinding__mdt/fields/BindingSObject__c.field-meta.xml
<CustomField>
    <fullName>BindingSObject__c</fullName>
    <description>The SObject that this Application Factory Domain Binding is mapped to.</description>
    <inlineHelpText>The SObject that this Application Factory Domain Binding is mapped to.</inlineHelpText>
    <label>Binding SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>ApplicationFactory_DomainBindings</relationshipLabel>
    <relationshipName>ApplicationFactory_DomainBindings</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/schema/objects/ApplicationFactory_DomainBinding__mdt/fields/BindingSObjectAlternate__c.field-meta.xml
<CustomField>
    <fullName>BindingSObjectAlternate__c</fullName>
    <description>Use this field to specify the SObject API name to bind to when the &quot;Binding SObject&quot; field does not list that particular SObject.  Only specify the &quot;Binding SObject&quot; field or this one; not both.</description>
    <inlineHelpText>Use this field to specify the SObject API name to bind to when the &quot;Binding SObject&quot; field does not list that particular SObject.  Only specify the &quot;Binding SObject&quot; field or this one; not both.</inlineHelpText>
    <label>Binding SObject Alternate</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/common-base/main/schema/objects/ApplicationFactory_DomainBinding__mdt/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>The Domain implementation class that is an implementation of the IApplicationSObjectDomain</description>
    <inlineHelpText>The Domain implementation class that is an implementation of the IApplicationSObjectDomain</inlineHelpText>
    <label>To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/classes/framework-application-factory/ApplicationSObjectDomainDIModule.cls
/**
 *
 * di_Module based class used to manage the Application Factory mappings of for the SOBject
 */
public class ApplicationSObjectDomainDIModule 
    extends di_Module
{
    public override void configure() 
    {
        Schema.DescribeSobjectResult[] results = null;

        String bindingSObjectAPIName = null;

        list<ApplicationFactory_DomainBinding__mdt> bindingRecords = [select DeveloperName, QualifiedAPIName, To__c
                                                                           , BindingSObject__c, BindingSObject__r.QualifiedApiName, BindingSObjectAlternate__c
                                                                        from ApplicationFactory_DomainBinding__mdt];

        for ( ApplicationFactory_DomainBinding__mdt bindingConfig : bindingRecords)
        {
            bindingSObjectAPIName = String.isNotBlank(bindingConfig.BindingSObject__c) ? bindingConfig.BindingSObject__r.QualifiedApiName : bindingConfig.BindingSObjectAlternate__c;

            apex();
            if (String.isNotBlank(bindingSObjectAPIName)) 
            {
                results = Schema.describeSObjects(new String[] { bindingSObjectAPIName.toLowerCase().trim() });
                if(results.size() != 1) 
                {
                    throw new di_Injector.InjectorException('Failed to find SObject ' + bindingSObjectAPIName 
                                                                 + ' referened by binding ' + bindingConfig.DeveloperName 
                                                                 + ' for ApplicationSObjectDomainDIModule di_Injectory module.');
                }
                bind(results[0].getSObjectType());
                bind(IApplicationSObjectDomain.class);
            }
            data(bindingConfig);
            to(bindingConfig.To__c);
        }
    }
}