sfdx-source/common-base/main/schema/objects/ApplicationFactory_ServiceBinding__mdt/ApplicationFactory_ServiceBinding__mdt.object-meta.xml
<CustomObject>
    <description>All Force-DI bindings for Services to the ApplicationSObjectServiceDIModule</description>
    <label>ApplicationFactory_ServiceBinding</label>
    <pluralLabel>ApplicationFactory_ServiceBindings</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/ApplicationFactory_ServiceBinding__mdt/fields/BindingInterface__c.field-meta.xml
<CustomField>
    <fullName>BindingInterface__c</fullName>
    <description>The Service Interface that this Application Factory Service Binding is mapped to.</description>
    <inlineHelpText>The Service Interface that this Application Factory Service Binding is mapped to.</inlineHelpText>
    <label>Binding Interface</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/ApplicationFactory_ServiceBinding__mdt/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>The Service implementation class that this binding is mapped to.</description>
    <inlineHelpText>The Service implementation class that this binding is mapped to.</inlineHelpText>
    <label>To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/classes/framework-application-factory/ApplicationServiceDIModule.cls
/**
 * Copyright (c) 2018, John M. Daniel
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *      this list of conditions and the following disclaimer in the documentation 
 *      and/or other materials provided with the distribution.
 * - Neither the name of the John M. Daniel, nor the names of its contributors 
 *      may be used to endorse or promote products derived from this software without 
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 *
 * di_Module based class used to manage the Application Factory mappings of for services
 */
public class ApplicationServiceDIModule 
    extends di_Module
{
    public override void configure() 
    {
        Type interfaceType = null;

        for ( ApplicationFactory_ServiceBinding__mdt bindingConfig : [select DeveloperName, QualifiedAPIName, To__c, BindingInterface__c 
                                                                         from ApplicationFactory_ServiceBinding__mdt])
        {
            apex();
            try {
                Type.forName(bindingConfig.BindingInterface__c);
            } catch (TypeException te) {
                throw new di_Injector.InjectorException('Service Interface ' + bindingConfig.BindingInterface__c + ' referened by binding ' + bindingConfig.DeveloperName + ' does not exist.');
            }
            bind(bindingConfig.BindingInterface__c);
            data(bindingConfig);
            to(bindingConfig.To__c);
        }
    }
}