sfdx-source/core/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/SelectorConfig_FieldSetInclusion__mdt.object-meta.xml
<CustomObject>
    <description>Defines a SObject fieldset that should be added to a selector&apos;s defined fields.</description>
    <label>Selector Config - Fieldset Inclusion</label>
    <pluralLabel>Selector Config - Fieldset Inclusions</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <description>The name of the fieldset containing the items that will be added to the selector.</description>
    <inlineHelpText>The name of the fieldset containing the items that will be added to the selector.</inlineHelpText>
    <label>Fieldset Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked (true), the fieldset&apos;s items will be added to the respective selector.  Otherwise, the fieldset will be ignored.</description>
    <inlineHelpText>If checked (true), the fieldset&apos;s items will be added to the respective selector.  Otherwise, the fieldset will be ignored.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>Specifies the selector, via the SObject Type, to which the fieldset&#39;s items will be added.</description>
    <inlineHelpText>Specifies the selector, via the SObject Type, to which the fieldset&#39;s items will be added.</inlineHelpText>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Selector_Config_Fieldset_Inclusions</relationshipLabel>
    <relationshipName>Selector_Config_Fieldset_Inclusions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/core/main/classes/framework-application-factory/ApplicationSelectorFieldsetDIModule.cls
public class ApplicationSelectorFieldsetDIModule
    extends di_Module
{
    private static Map<SObjectType, Set<String>> FIELDSETNAMES_BY_SOBJECTTYPE_MAP;

    static 
    {
        FIELDSETNAMES_BY_SOBJECTTYPE_MAP = new Map<SObjectType, Set<String>>();

        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();

        SObjectType soType = null;

        for (SelectorConfig_FieldSetInclusion__mdt scfi : [select Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName
                                                            , SObjectType__c, FieldsetName__c
                                                         from SelectorConfig_FieldSetInclusion__mdt
                                                        where IsActive__c = true
                                                        order by SObjectType__c, Fieldsetname__c] )
        {
            soType = globalDescribeMap.get(scfi.SObjectType__c.toLowerCase());

            if ( soType != null )
            {
                if ( ! FIELDSETNAMES_BY_SOBJECTTYPE_MAP.containsKey(soType) )
                {
                    FIELDSETNAMES_BY_SOBJECTTYPE_MAP.put(soType, new Set<String>());
                }

                // if the fieldset name does exist
                if( soType.getDescribe().fieldSets.getMap().containsKey( scfi.FieldsetName__c.toLowerCase() ) )
                {
                    // ... then add the fieldset to the map
                    FIELDSETNAMES_BY_SOBJECTTYPE_MAP.get(soType).add( scfi.FieldsetName__c.toLowerCase() );
                }
            }
        }
    }

    public override void configure() 
    {
        // loop through the FIELDSETNAMES_BY_SOBJECTTYPE_MAP // Map<SObjectType, Set<String>>
        for (SObjectType sobjTypeKey : FIELDSETNAMES_BY_SOBJECTTYPE_MAP.keySet())
        {
            for ( String fieldSetName : FIELDSETNAMES_BY_SOBJECTTYPE_MAP.get( sobjTypeKey ) )
            {
                apex().bind( sobjTypeKey ).bind( Schema.Fieldset.class )
                    .to( fieldSetName );
            }
        }
    }
}