sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/SelectorConfig_FieldSetInclusion__mdt.object-meta.xml
<CustomObject>
    <description>Defines a SObject fieldset that should be added to a selector&#39;s defined fields.</description>
    <label>Selector Config - Fieldset Inclusion</label>
    <pluralLabel>Selector Config - Fieldset Inclusions</pluralLabel>
</CustomObject>

sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <description>The name of the fieldset containing the items that will be added to the selector.</description>
    <inlineHelpText>The name of the fieldset containing the items that will be added to the selector.</inlineHelpText>
    <label>Fieldset Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked (true), the fieldset&#39;s items will be added to the respective selector.  Otherwise, the fieldset will be ignored.</description>
    <inlineHelpText>If checked (true), the fieldset&#39;s items will be added to the respective selector.  Otherwise, the fieldset will be ignored.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/SelectorConfig_FieldSetInclusion__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>Specifies the selector, via the SObject Type, to which the fieldset&#39;s items will be added.</description>
    <inlineHelpText>Specifies the selector, via the SObject Type, to which the fieldset&#39;s items will be added.</inlineHelpText>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Selector_Config_Fieldset_Inclusions</relationshipLabel>
    <relationshipName>Selector_Config_Fieldset_Inclusions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/common-base/main/classes/framework/ApplicationSelectorFieldsetDIModule.cls
public class ApplicationSelectorFieldsetDIModule
    extends di_Module
{
    public override void configure() 
    {
        Map<SObjectType, Map<String, Schema.FieldSet>> fieldsetMap = new Map<SObjectType, Map<String, Schema.FieldSet>>();

        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();

        for (SelectorConfig_FieldSetInclusion__mdt scfi : getConfigurationRecords())
        {
            SObjectType soType = globalDescribeMap.get(scfi.SObjectType__c.toLowerCase());

            if (soType != null)
            {
                if (!fieldsetMap.containsKey(soType))
                {
                    fieldsetMap.put(soType, new Map<String, Schema.FieldSet>());
                    for (Fieldset fs : soType.getDescribe().fieldSets.getMap().values())
                    {
                        fieldsetMap.get(soType).put(fs.getName().toLowerCase(), fs);
                    }
                }
                else
                {
                    System.debug(
                        LoggingLevel.ERROR, 
                        'SelectorConfig_FieldSetInclusion record, ' + scfi.DeveloperName + 
                        ', specifies field set named, ' + scfi.FieldsetName__c + 
                        ', which was not found for SObject Type, ' + scfi.SObjectType__c);
                }
            }
            else
            {
                System.debug(
                    LoggingLevel.ERROR, 
                    'SelectorConfig_FieldSetInclusion record, ' + scfi.DeveloperName + 
                    ', specifies SObject Type, ' + scfi.SObjectType__c +
                    ', but was not found');
            }
        }

        System.debug(
            LoggingLevel.DEBUG,
            getConfigurationRecords() + '\n' +
            globalDescribeMap + '\n' +
            fieldsetMap
        );

        for (SelectorConfig_FieldSetInclusion__mdt scfi : getConfigurationRecords())
        {
            SObjectType soType = globalDescribeMap.get(scfi.SObjectType__c);

            if (!fieldsetMap.containsKey(soType)) continue;
            if (!fieldsetMap.get(soType).containsKey(scfi.FieldsetName__c.toLowerCase())) continue;

            apex();
            bind(globalDescribeMap.get(scfi.SObjectType__c));
            bind(Schema.Fieldset.class);
            data(scfi);
            to(fieldsetMap.get(soType).get(scfi.FieldsetName__c.toLowerCase()).getName());
        }

        System.debug(LoggingLevel.DEBUG, di_Injector.Org.Bindings.get());
    }

    private List<SelectorConfig_FieldSetInclusion__mdt> configurationRecords = null;

    private List<SelectorConfig_FieldSetInclusion__mdt> getConfigurationRecords()
    {
        if (configurationRecords == null)
        {
            configurationRecords =
            [
                select
                    Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, 
                    SObjectType__c, FieldsetName__c
                from SelectorConfig_FieldSetInclusion__mdt
                where IsActive__c = true
                order by SObjectType__c, Fieldsetname__c
            ];
        }

        return configurationRecords;
    }
}