sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/PlatformEvents_Distribution__mdt.object-meta.xml
<CustomObject>
    <description>Maintains the list of Platform-Event consumers.</description>
    <label>Platform Events - Distribution</label>
    <pluralLabel>Platform Events - Distributions</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/fields/RelatedPlatformEventBus__c.field-meta.xml
<CustomField>
    <fullName>RelatedPlatformEventBus__c</fullName>
    <description>Required value specifying the platform event bus for matching to desired events, i.e. &quot;Sales&quot;, &quot;Marketing&quot;.</description>
    <inlineHelpText>Required value specifying the platform event bus for matching to desired events, i.e. &quot;Sales&quot;, &quot;Marketing&quot;.</inlineHelpText>
    <label>Related Platform Event Bus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/classes/framework-platform-event-distributor/PlatformEventDistributor.cls
public class PlatformEventDistributor
{
    private enum MatcherRules
    {
        MatchPlatformEventBusAndRelatedSObjectAndEventName,
        MatchPlatformEventBusAndRelatedSObject,
        MatchPlatformEventBusandEventName,
        MatchPlatformEventBus
    }

    private Map<String, List<PlatformEvents_Distribution__mdt>> eventBusToConfigurationMap = new Map<String, List<PlatformEvents_Distribution__mdt>>();

    public PlatformEventDistributor()
    {
        Map<String, List<PlatformEvents_Distribution__mdt>> eventBusToConfigurationMap = new Map<String, List<PlatformEvents_Distribution__mdt>>();

        for (di_Binding binding : di_Injector.Org.Bindings.byName(IEventsConsumer.class.getName()).get())
        {
            PlatformEvents_Distribution__mdt pedConfig = (PlatformEvents_Distribution__mdt) binding.Data;

            if (!eventBusToConfigurationMap.containsKey(pedConfig.RelatedPlatformEventBus__c))
            {
                eventBusToConfigurationMap.put(pedConfig.RelatedPlatformEventBus__c, new List<PlatformEvents_Distribution__mdt>());
            }

            eventBusToConfigurationMap.get(pedConfig.RelatedPlatformEventBus__c).add(pedConfig);

            System.debug(eventBusToConfigurationMap);
        }
    }

    public static void triggerHandler()
    {
        if (Trigger.isExecuting && Trigger.isAfter && Trigger.isInsert)
        {
            triggerHandler(trigger.new);
        }
    }

    @TestVisible
    private static void triggerHandler(List<SObject> events)
    {

    }
}