sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/PlatformEvents_Distribution__mdt.object-meta.xml
<CustomObject>
    <description>Maintains the list of Platform-Event consumers.</description>
    <label>Platform Events - Distribution</label>
    <pluralLabel>Platform Events - Distributions</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/fields/Consumer__c.field-meta.xml
<CustomField>
    <fullName>Consumer__c</fullName>
    <description>The name of the Apex Class that implements mmlib_IEventConsumer that the subscription is operating on behalf of.</description>
    <inlineHelpText>The name of the Apex Class that implements mmlib_IEventConsumer that the subscription is operating on behalf of.</inlineHelpText>
    <label>Consumer</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/fields/EventBus__c.field-meta.xml
<CustomField>
    <fullName>EventBus__c</fullName>
    <description>Specifies the event&#39;s SObject Type that the consumer desires.</description>
    <inlineHelpText>Specifies the event&#39;s SObject Type that the consumer desires.</inlineHelpText>
    <label>Event Bus</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Distribution__mdt/fields/MatcherRule__c.field-meta.xml
<CustomField>
    <fullName>MatcherRule__c</fullName>
    <description>This determines which fields must match the event in order for it to be distributed to the consumer.</description>
    <inlineHelpText>This determines which fields must match the event in order for it to be distributed to the consumer.</inlineHelpText>
    <label>Matcher Rule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Match Platform Event Bus and Related SObject and Event Name</fullName>
                <default>true</default>
                <label>Match Platform Event Bus and Related SObject and Event Name</label>
            </value>
            <value>
                <fullName>Match Platform Event Bus and Related SObject</fullName>
            </value>
            <value>
                <fullName>Match Platform Event Bus and Event Name</fullName>
            </value>
            <value>
                <fullName>Match Platform Event Bus Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/classes/framework-platform-event-distributor/PlatformEventDistributorDIModule.cls
public class PlatformEventDistributorDIModule
    extends di_Module
{
    public override void configure()
    {
        Schema.DescribeSobjectResult[] results = null;

        for (ConfigWrapper bindingConfigWrapper : getConfigurationList())
        {
            // Validate the distribution record first.

            if (String.isBlank(bindingConfigWrapper.EventBus))
            {
                System.debug(
                    LoggingLevel.WARN, 
                    SObjectType.PlatformEvents_Distribution__mdt.getLabel() + ' record named, ' + bindingConfigWrapper.DeveloperName +
                    ', does not have required field, ' + PlatformEvents_Distribution__mdt.EventBus__c.getDescribe().getLabel());
                continue;
            }

            if (String.isBlank(bindingConfigWrapper.Consumer))
            {
                System.debug(
                    LoggingLevel.WARN, 
                    SObjectType.PlatformEvents_Distribution__mdt.getLabel() + ' record named, ' + bindingConfigWrapper.DeveloperName +
                    ', does not have required field, ' + PlatformEvents_Distribution__mdt.Consumer__c.getDescribe().getLabel());
                continue;
            }

            apex();
            bind(bindingConfigWrapper.EventBus);
            bind(IEventsConsumer.class);
            data(bindingConfigWrapper.record);
            to(bindingConfigWrapper.Consumer);
        }
    }

    @TestVisible
    private List<ConfigWrapper> getConfigurationList()
    {
        List<ConfigWrapper> result = new List<ConfigWrapper>();

        for (
            PlatformEvents_Distribution__mdt bindingConfig
            :
            [select 
                DeveloperName, Consumer__c, Event__c , EventCategory__c, MatcherRule__c, EventBus__c 
                from PlatformEvents_Distribution__mdt where IsActive__c = true]
        )
        {
            result.add(new ConfigWrapper(bindingConfig));
        }

        if (mock_BindingConfigurationWrappers != null) result = mock_BindingConfigurationWrappers;

        return result;
    }

    @TestVisible
    private class ConfigWrapper
    {
        public String DeveloperName = null;
        public String Consumer = null;
        public String Event = null;
        public String EventCategory = null;
        public String MatcherRule = null;
        public String EventBus = null;
        public PlatformEvents_Distribution__mdt record = null;

        public ConfigWrapper(PlatformEvents_Distribution__mdt bindingConfig)
        {
            this.DeveloperName = bindingConfig.DeveloperName;
            this.Consumer = bindingConfig.Consumer__c;
            this.Event = bindingConfig.Event__c;
            this.EventCategory = bindingConfig.EventCategory__c;
            this.MatcherRule = bindingConfig.MatcherRule__c;
            this.EventBus = bindingConfig.EventBus__c;
            this.record = bindingConfig;
        }

        @TestVisible
        private ConfigWrapper(
            String DeveloperName,
            String Consumer,
            String Event,
            String EventCategory,
            String MatcherRule,
            String EventBus
        )
        {
            this.DeveloperName = DeveloperName;
            this.Consumer = Consumer;
            this.Event = Event;
            this.EventCategory = EventCategory;
            this.MatcherRule = MatcherRule;
            this.EventBus = EventBus;
            this.record = new PlatformEvents_Distribution__mdt();
        }
    }

    @TestVisible
    List<ConfigWrapper> mock_BindingConfigurationWrappers = null;
}