sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/DomainProcessBinding__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is responsible for controlling the dependency injection of domain criteria and actions.</description>
    <label>Domain Process Binding</label>
    <pluralLabel>Domain Process Bindings</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/ClassToInject__c.field-meta.xml
<CustomField>
    <fullName>ClassToInject__c</fullName>
    <description>This is the Apex class that will be injected into the process execution.  If the domain process type is &quot;Criteria&quot;, then the class has to implement mmlib_ICriteria or mmlib_ICriteriaWithExistingRecords.  If the domain process type is &quot;Action&quot;, then the class has to implement mmlib_IAction.</description>
    <inlineHelpText>This is the Apex class that will be injected into the process execution.</inlineHelpText>
    <label>Class To Inject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Brief description of why this is present.</description>
    <inlineHelpText>Brief description of why this is present.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/DomainMethodToken__c.field-meta.xml
<CustomField>
    <fullName>DomainMethodToken__c</fullName>
    <description>In a process context of Domain Method Execution, you will need to provide a Domain Method Token -- some unique string that will be supplied to the dependency injection process from the domain class method.</description>
    <inlineHelpText>In a process context of Domain Method Execution, you will need to provide a Domain Method Token -- some unique string that will be supplied to the dependency injection process from the domain class method.</inlineHelpText>
    <label>Domain Method Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/common-base/main/schema/objects/DomainProcessBinding__mdt/fields/ExecuteAsynchronous__c.field-meta.xml
<CustomField>
    <fullName>ExecuteAsynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then the action will be executed in Queueable context and not the primary execution thread.</description>
    <inlineHelpText>If checked, then the action will be executed in Queueable context and not the primary execution thread.</inlineHelpText>
    <label>Execute Asynchronous</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this is unchecked, this criteria or action will be ignored by the process.</description>
    <inlineHelpText>If this is unchecked, this criteria or action will be ignored by the process.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/LogicalInverse__c.field-meta.xml
<CustomField>
    <fullName>LogicalInverse__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then the logical inverse of the associated criteria will be used for the criteria.  Basically, instead of the criteria retaining the records, those records will be filtered out of the working set.</description>
    <inlineHelpText>If checked, then the logical inverse of the associated criteria will be used for the criteria.  Basically, instead of the criteria retaining the records, those records will be filtered out of the working set.</inlineHelpText>
    <label>Logical Inverse</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/OrderOfExecution__c.field-meta.xml
<CustomField>
    <fullName>OrderOfExecution__c</fullName>
    <description>Within a process context and &quot;trigger operation&quot;/&quot;domain method token&quot;, you will have one or more criteria and one or more actions.  This allows you to specify what the execution order is.  If more than one sequence of criteria and actions are required, then designate this by using decimal numbers.  i.e. 1.1-criteria, 1.2-critera, 1.3-action, 2.1-criteria, 2.2-action</description>
    <inlineHelpText>Within a process context and &quot;trigger operation&quot;/&quot;domain method token&quot;, you will have one or more criteria and one or more actions.  This allows you to specify what the execution order is.</inlineHelpText>
    <label>Order Of Execution</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/ProcessContext__c.field-meta.xml
<CustomField>
    <fullName>ProcessContext__c</fullName>
    <description>Represents what type of process will be initiating the execution of the criteria and actions.</description>
    <inlineHelpText>Represents what type of process will be initiating the execution of the criteria and actions.</inlineHelpText>
    <label>Process Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DomainMethodExecution</fullName>
                <label>Domain Method Execution</label>
            </value>
            <value>
                <fullName>TriggerExecution</fullName>
                <default>true</default>
                <label>Trigger Execution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/RelatedDomainBindingSObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedDomainBindingSObject__c</fullName>
    <label>Related Domain SObject Binding</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Domain_Processes</relationshipLabel>
    <relationshipName>Domain_Processes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/TriggerOperation__c.field-meta.xml
<CustomField>
    <fullName>TriggerOperation__c</fullName>
    <description>For a process context of &quot;trigger execution&quot;, you need to specify which trigger operation this criteria or action would respond to.</description>
    <inlineHelpText>For a process context of &quot;trigger execution&quot;, you need to specify which trigger operation this criteria or action would respond to.</inlineHelpText>
    <label>Trigger Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before_Insert</fullName>
                <default>true</default>
                <label>Before Insert</label>
            </value>
            <value>
                <fullName>After_Insert</fullName>
                <label>After Insert</label>
            </value>
            <value>
                <fullName>Before_Update</fullName>
                <label>Before Update</label>
            </value>
            <value>
                <fullName>After_Update</fullName>
                <label>After Update</label>
            </value>
            <value>
                <fullName>Before_Delete</fullName>
                <label>Before Delete</label>
            </value>
            <value>
                <fullName>After_Delete</fullName>
                <label>After Delete</label>
            </value>
            <value>
                <fullName>After_Undelete</fullName>
                <label>After Undelete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Domain processes are composed of criteria and actions -- which type is this entry??</description>
    <inlineHelpText>Domain processes are composed of criteria and actions -- which type is this entry??</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Criteria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/classes/framework-domain-process-injection/DomainProcessCoordinator.cls
public class DomainProcessCoordinator 
{
    private Schema.DescribeSObjectResult sObjectDescribe = null;

    // The domainProcessMap organizes all of the domain process custom metadata record entries
    // The map is organized by ProcessContext__c, DomainMethodToken__c/TriggerOperation__c, "Sequence" (infered from the OrderOfExecution__c), Type__c, OrderOfExecution__c, --- DomainProcessBinding__mdt record which contains the ClassToInject__c
    private Map<DomainProcessConstants.PROCESS_CONTEXT, Map<String, Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>>>> domainProcessMap = new Map<DomainProcessConstants.PROCESS_CONTEXT, Map<String, Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>>>>();

    private Map<DomainProcessConstants.PROCESS_CONTEXT, Map<String, Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>>>> getDomainProcessMap()
    {
        //system.debug( 'getDomainProcessMap() called');
        if ( this.domainProcessMap.isEmpty() )
        {
            // system.debug( 'domainProcessMap found to be empty.  Now prime the relevant Domain Logic Injections records');
            primeDomainLogicInjections();
        }
        return this.domainProcessMap;
    }

    @TestVisible
    private list<DomainProcessBinding__mdt> mockDomainProcesses = new list<DomainProcessBinding__mdt>();

    private void primeDomainLogicInjections()
    {
        // find all process DomainProcessBinding__mdt records that are related
        list<DomainProcessBinding__mdt> domainProcesses = [select Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName
                                                         , ClassToInject__c, Description__c, DomainMethodToken__c, ExecuteAsynchronous__c, IsActive__c
                                                         , LogicalInverse__c, OrderOfExecution__c, PreventRecursive__c, ProcessContext__c
                                                         , RelatedDomainBindingSObject__c, TriggerOperation__c, Type__c
                                                      from DomainProcessBinding__mdt
                                                     where RelatedDomainBindingSObject__c = :this.sObjectDescribe.getName()
                                                       and IsActive__c = true
                                                     order by ProcessContext__c, TriggerOperation__c, OrderOfExecution__c, Type__c];

        //if (System.Test.isRunningTest() && mockDomainProcesses != null)
        //system.debug( 'this.mockDomainProcesses == ' + this.mockDomainProcesses );

// TODO : Figure out how mock domain processes should be handled
        if ( ! this.mockDomainProcesses.isEmpty() )
        {
            domainProcesses.clear();
            domainProcesses.addAll( mockDomainProcesses );
            //system.debug( 'this.mockDomainProcesses == ' + this.mockDomainProcesses );
        }

        DomainProcessConstants.PROCESS_CONTEXT processContext = null;
        String domainProcessToken = null;
        Integer sequence = null;
        DomainProcessConstants.PROCESS_TYPE processType = null;

        // need to sort these domainProcesses by ProcessContext__c, DomainMethodToken__c/TriggerOperation__c, "Sequence" (infered from the OrderOfExecution__c), Type__c, OrderOfExecution__c, --- ClassToInject__c
        //                                    map< string,          map< string,                              map< integer,                                      map< string, map< decimal, String> > > > >
        for ( DomainProcessBinding__mdt domainProcess : domainProcesses )
        {
            processContext = DomainProcessConstants.PROCESS_CONTEXT.TriggerExecution.name().equalsIgnoreCase( domainProcess.ProcessContext__c ) ? DomainProcessConstants.PROCESS_CONTEXT.TriggerExecution : DomainProcessConstants.PROCESS_CONTEXT.DomainMethodExecution;

            if ( ! domainProcessMap.containsKey( processContext ) )
            {
                domainProcessMap.put( processContext, new Map<String, Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>>>() );
            }

            domainProcessToken = string.isBlank( domainProcess.DomainMethodToken__c ) ? domainProcess.TriggerOperation__c : domainProcess.DomainMethodToken__c;

            if ( ! domainProcessMap.get( processContext ).containsKey( domainProcessToken ) )
            {
                domainProcessMap.get( processContext ).put( domainProcessToken, new Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>>() );
            }

            sequence = Integer.valueOf( domainProcess.OrderOfExecution__c );

            if ( ! domainProcessMap.get( processContext ).get( domainProcessToken ).containsKey( sequence ) )
            {
                domainProcessMap.get( processContext ).get( domainProcessToken ).put( sequence, new Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>() );
            }

            processType = DomainProcessConstants.PROCESS_TYPE.CRITERIA.name().equalsIgnoreCase( domainProcess.Type__c ) ? DomainProcessConstants.PROCESS_TYPE.CRITERIA : DomainProcessConstants.PROCESS_TYPE.ACTION;

            if ( ! domainProcessMap.get( processContext ).get( domainProcessToken ).get( sequence ).containsKey( processType ) )
            {
                domainProcessMap.get( processContext ).get( domainProcessToken ).get( sequence ).put( processType, new Map<Decimal, DomainProcessBinding__mdt>() );
            }

            domainProcessMap.get( processContext ).get( domainProcessToken ).get( sequence ).get( processType ).put( domainProcess.OrderOfExecution__c, domainProcess );
        }
    }

    public DomainProcessCoordinator(Schema.DescribeSObjectResult sObjectDescribe) 
    {
        if ( sObjectDescribe == null )
        {

        }
        this.sObjectDescribe = sObjectDescribe;
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(String domainProcessToken )
    {
        processDomainLogicInjections( DomainProcessConstants.PROCESS_CONTEXT.DomainMethodExecution, domainProcessToken, null, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(String domainProcessToken, IApplicationSObjectUnitOfWork uow )
    {
        processDomainLogicInjections( DomainProcessConstants.PROCESS_CONTEXT.DomainMethodExecution, domainProcessToken, null, uow );
    }

    public void processDomainLogicInjections(DomainProcessConstants.PROCESS_CONTEXT processContext, System.TriggerOperation triggerOperationType )
    {
        processDomainLogicInjections( processContext, triggerOperationType.name(), null, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(DomainProcessConstants.PROCESS_CONTEXT processContext, String domainProcessToken )
    {
        processDomainLogicInjections( processContext, domainProcessToken, null, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(String domainProcessToken, Map<Id,SObject> existingRecords )
    {
        processDomainLogicInjections( DomainProcessConstants.PROCESS_CONTEXT.DomainMethodExecution, domainProcessToken, existingRecords, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(String domainProcessToken, Map<Id,SObject> existingRecords, IApplicationSObjectUnitOfWork uow )
    {
        processDomainLogicInjections( DomainProcessConstants.PROCESS_CONTEXT.DomainMethodExecution, domainProcessToken, existingRecords, uow );
    }

    public void processDomainLogicInjections(DomainProcessConstants.PROCESS_CONTEXT processContext, System.TriggerOperation triggerOperationType, Map<Id,SObject> existingRecords )
    {
        processDomainLogicInjections( processContext, triggerOperationType.name(), existingRecords, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(DomainProcessConstants.PROCESS_CONTEXT processContext, String domainProcessToken, Map<Id,SObject> existingRecords )
    {
        processDomainLogicInjections( processContext, domainProcessToken, existingRecords, null );
    }

    /**
    *  Call this method either from a domain class method or it is automatically called from trigger context
    *  and any criteria and actions for that combination will be executed.
    */
    public void processDomainLogicInjections(DomainProcessConstants.PROCESS_CONTEXT processContext, String domainProcessToken, Map<Id,SObject> existingRecords, IApplicationSObjectUnitOfWork uow )
    {
    }
//         system.debug( 'mark 1 -- processContext : ' + processContext +  ' -- domainProcessToken : ' + domainProcessToken);
//         if ( getDomainProcessMap().containsKey( processContext )
//             && getDomainProcessMap().get( processContext ).containsKey( domainProcessToken ) )
//         {
//             // There is a process context that matches the parameters
// 
//             // The domainProcessesToExecuteMap is comprised of the following data points:
//             //  Sequence --------------------------------------------------------------- Sequence
//             //  |            Type__c --------------------------------------------------- Type__c
//             //  |            |                 OrderOfExecution__c --------------------- OrderOfExecution__c
//             //  |            |                 |        DomainProcessBinding__mdt ------------- DomainProcessBinding__mdt
//             //  |            |                 |        |
//             Map<Integer, Map<DomainProcessConstants.PROCESS_TYPE, Map<Decimal, DomainProcessBinding__mdt>>> domainProcessesToExecuteMap = getDomainProcessMap().get( processContext ).get( domainProcessToken );
// 
//             List<SObject> qualifiedRecords = new List<SObject>();
// 
//             List<Integer> sequenceKeysSorted = new List<Integer>( domainProcessesToExecuteMap.keySet() );
// 
//             sequenceKeysSorted.sort();
// 
//             List<Decimal> orderOfExecutionKeysSorted = new List<Decimal>();
// 
//             Type classToInject = null;
// 
//             mmlib_ICriteria criteriaClazz = null;
//             mmlib_IAction actionClazz = null;
// 
//             DomainProcessBinding__mdt currentDomainProcess = null;
// 
//             for( Integer sequenceKey : sequenceKeysSorted )
//             {
//                 system.debug('Starting sequence ' + sequenceKey + ' for processContext ' + processContext + ' and domainProcessToken ' + domainProcessToken);
// 
//                 // reset the qualifiedRecords
//                 qualifiedRecords.clear();
// 
//                 // process the criterias first
//                 if ( domainProcessesToExecuteMap.get( sequenceKey ).containsKey( DomainProcessConstants.PROCESS_TYPE.CRITERIA ) )
//                 {
//                     // process the criteria
// 
//                     // reset the orderOfExecutionKeysSorted
//                     orderOfExecutionKeysSorted.clear();
// 
//                     orderOfExecutionKeysSorted = new List<Decimal>( domainProcessesToExecuteMap.get( sequenceKey ).get( DomainProcessConstants.PROCESS_TYPE.CRITERIA ).keySet() );
// 
//                     orderOfExecutionKeysSorted.sort();
// 
//                     qualifiedRecords.addAll( this.records );
// 
//                     for ( Decimal orderOfExecutionKey : orderOfExecutionKeysSorted )
//                     {
//                         currentDomainProcess = domainProcessesToExecuteMap.get( sequenceKey ).get( DomainProcessConstants.PROCESS_TYPE.CRITERIA ).get( orderOfExecutionKey );
//                         system.debug( 'processing criteria class ' + currentDomainProcess.ClassToInject__c );
// 
//                         classToInject = Type.forName( currentDomainProcess.ClassToInject__c );
// 
//                         if ( classToInject == null )
//                         {
//                             throw new ProcessInjectionException('Unable to find class type of \'' + currentDomainProcess.ClassToInject__c + '\'');
//                         }
// 
//                         try
//                         {
//                             // newInstance from here
//                             criteriaClazz = (mmlib_ICriteria) classToInject.newInstance();
// 
//                             criteriaClazz.setRecordsToEvaluate( qualifiedRecords );
// 
//                             if ( criteriaClazz instanceOf mmlib_ICriteriaWithExistingRecords
//                                 && existingRecords != null
//                                 && ! existingRecords.isEmpty() )
//                             {
//                                 ((mmlib_ICriteriaWithExistingRecords)criteriaClazz).setExistingRecords( existingRecords );
//                             }
// // TODO: Still need to figure out how to make use of currentDomainProcess.LogicalInverse__c here.
//                             qualifiedRecords = criteriaClazz.run();
//                         }
//                         catch (Exception e)
//                         {
//                             system.debug( e );
//                             throw new ProcessInjectionException( e );
//                         }
// 
//                         // if all records have been removed from qualification, then exit out of the loop
//                         if ( qualifiedRecords.isEmpty() )
//                         {
//                             system.debug( 'no qualified records were found');
//                             break;
//                         }
//                     }
//                 }
//                 else
//                 {
//                     // no criteria found in this sequence
//                     // set the qualifiedRecords to the domain's records
//                     qualifiedRecords.addAll( this.records );
//                 }
// 
//                 system.debug( logginglevel.FINE, qualifiedRecords );
//                 system.debug( logginglevel.FINE, sequenceKey );
// 
//                 // process the actions last
//                 if ( domainProcessesToExecuteMap.get( sequenceKey ).containsKey( DomainProcessConstants.PROCESS_TYPE.ACTION )
//                     && ! qualifiedRecords.isempty() )
//                 {
//                     System.debug('processing actions');
//                     // reset the orderOfExecutionKeysSorted
//                     orderOfExecutionKeysSorted.clear();
// 
//                     orderOfExecutionKeysSorted = new List<Decimal>( domainProcessesToExecuteMap.get( sequenceKey ).get( DomainProcessConstants.PROCESS_TYPE.ACTION ).keySet() );
// 
//                     orderOfExecutionKeysSorted.sort();
// 
//                     classToInject = null;
// 
//                     for ( Decimal orderOfExecutionKey : orderOfExecutionKeysSorted )
//                     {
//                         currentDomainProcess = domainProcessesToExecuteMap.get( sequenceKey ).get( DomainProcessConstants.PROCESS_TYPE.ACTION ).get( orderOfExecutionKey );
//                         system.debug( 'processing action class ' + currentDomainProcess.ClassToInject__c );
// 
//                         classToInject = Type.forName( currentDomainProcess.ClassToInject__c );
// 
//                         if ( classToInject == null )
//                         {
//                             throw new ProcessInjectionException('Unable to find class type of \'' + currentDomainProcess.ClassToInject__c + '\'');
//                         }
// 
//                         try
//                         {
//                             // newInstance from here
//                             actionClazz = (mmlib_IAction) classToInject.newInstance();
// 
//                             actionClazz.setRecordsToActOn( qualifiedRecords );
// 
//                             // Should the action process execute in async/queueable mode?
//                             if ( currentDomainProcess.ExecuteAsynchronous__c )
//                             {
//                                 ((mmlib_IQueueableAction)actionClazz).setActionToRunInQueue( true );
//                             }
// 
//                             if ( actionClazz instanceOf mmlib_IUnitOfWorkable
//                                 && uow != null )
//                             {
//                                 ((mmlib_IUnitOfWorkable)actionClazz).setUnitOfWork( uow );
//                             }
// 
//                             actionClazz.run();
//                         }
//                         catch (Exception e)
//                         {
//                             system.debug( e );
//                             throw new ProcessInjectionException( e );
//                         }
//                     }
//                 }
//             }
//         }
//     }
// 
//     public class ProcessInjectionException extends Exception { }


}