sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/DomainProcessBinding__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is responsible for controlling the dependency injection of domain criteria and actions.</description>
    <label>Domain Process Binding</label>
    <pluralLabel>Domain Process Bindings</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/ClassToInject__c.field-meta.xml
<CustomField>
    <fullName>ClassToInject__c</fullName>
    <description>This is the Apex class that will be injected into the process execution.  If the domain process type is &quot;Criteria&quot;, then the class has to implement mmlib_ICriteria or mmlib_ICriteriaWithExistingRecords.  If the domain process type is &quot;Action&quot;, then the class has to implement mmlib_IAction.</description>
    <inlineHelpText>This is the Apex class that will be injected into the process execution.</inlineHelpText>
    <label>Class To Inject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this is unchecked, this criteria or action will be ignored by the process.</description>
    <inlineHelpText>If this is unchecked, this criteria or action will be ignored by the process.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/OrderOfExecution__c.field-meta.xml
<CustomField>
    <fullName>OrderOfExecution__c</fullName>
    <description>Within a process context and &quot;trigger operation&quot;/&quot;domain method token&quot;, you will have one or more criteria and one or more actions.  This allows you to specify what the execution order is.  If more than one sequence of criteria and actions are required, then designate this by using decimal numbers.  i.e. 1.1-criteria, 1.2-critera, 1.3-action, 2.1-criteria, 2.2-action</description>
    <inlineHelpText>Within a process context and &quot;trigger operation&quot;/&quot;domain method token&quot;, you will have one or more criteria and one or more actions.  This allows you to specify what the execution order is.</inlineHelpText>
    <label>Order Of Execution</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/ProcessContext__c.field-meta.xml
<CustomField>
    <fullName>ProcessContext__c</fullName>
    <description>Represents what type of process will be initiating the execution of the criteria and actions.</description>
    <inlineHelpText>Represents what type of process will be initiating the execution of the criteria and actions.</inlineHelpText>
    <label>Process Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DomainMethodExecution</fullName>
                <label>Domain Method Execution</label>
            </value>
            <value>
                <fullName>TriggerExecution</fullName>
                <default>true</default>
                <label>Trigger Execution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/RelatedDomainBindingSObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedDomainBindingSObject__c</fullName>
    <label>Related Domain SObject Binding</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Domain_Processes</relationshipLabel>
    <relationshipName>Domain_Processes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/TriggerOperation__c.field-meta.xml
<CustomField>
    <fullName>TriggerOperation__c</fullName>
    <description>For a process context of &quot;trigger execution&quot;, you need to specify which trigger operation this criteria or action would respond to.</description>
    <inlineHelpText>For a process context of &quot;trigger execution&quot;, you need to specify which trigger operation this criteria or action would respond to.</inlineHelpText>
    <label>Trigger Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before_Insert</fullName>
                <default>true</default>
                <label>Before Insert</label>
            </value>
            <value>
                <fullName>After_Insert</fullName>
                <label>After Insert</label>
            </value>
            <value>
                <fullName>Before_Update</fullName>
                <label>Before Update</label>
            </value>
            <value>
                <fullName>After_Update</fullName>
                <label>After Update</label>
            </value>
            <value>
                <fullName>Before_Delete</fullName>
                <label>Before Delete</label>
            </value>
            <value>
                <fullName>After_Delete</fullName>
                <label>After Delete</label>
            </value>
            <value>
                <fullName>After_Undelete</fullName>
                <label>After Undelete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/main/schema/objects/DomainProcessBinding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Domain processes are composed of criteria and actions -- which type is this entry??</description>
    <inlineHelpText>Domain processes are composed of criteria and actions -- which type is this entry??</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Criteria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/core/test/classes/framework-domain-process-injection/DomainProcessInjectionTest.cls
/**
 * Copyright (c) 2020, John M. Daniel & John Storey
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *      this list of conditions and the following disclaimer in the documentation 
 *      and/or other materials provided with the distribution.
 * - Neither the name of the John M. Daniel, nor the names of its contributors 
 *      may be used to endorse or promote products derived from this software without 
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

@IsTest
public class DomainProcessInjectionTest
{
    @isTest
    private static void accountInsertTwoCriteria() 
    {
        List<DomainProcessBinding__mdt> config = new List<DomainProcessBinding__mdt> {
            new DomainProcessBinding__mdt(
                Label = 'DallasAccountCriteria',
                ClassToInject__c = 'DomainProcessInjectionTest.AccountIsDallasCriteriaTest',
                IsActive__c = true,
                OrderOfExecution__c = 10.10,
                ProcessContext__c = 'Trigger Execution',
                RelatedDomainBindingSObject__c = 'Account',
                TriggerOperation__c = 'Before Insert',
                Type__c = 'Criteria'
            ),
            new DomainProcessBinding__mdt(
                Label = 'RichmondAccountCriteria',
                ClassToInject__c = 'DomainProcessInjectionTest.AccountIsRichmondCriteriaTest',
                IsActive__c = true,
                OrderOfExecution__c = 11.10,
                ProcessContext__c = 'Trigger Execution',
                RelatedDomainBindingSObject__c = 'Account',
                TriggerOperation__c = 'Before Insert',
                Type__c = 'Criteria'
            ),
            new DomainProcessBinding__mdt(
                Label = 'DallasAccountAction',
                ClassToInject__c = 'DomainProcessInjectionTest.DallasAccountActionTest',
                IsActive__c = true,
                OrderOfExecution__c = 10.10,
                ProcessContext__c = 'Trigger Execution',
                RelatedDomainBindingSObject__c = 'Account',
                TriggerOperation__c = 'Before Insert',
                Type__c = 'Action'
            ),
            new DomainProcessBinding__mdt(
                Label = 'RichmondAccountAction',
                ClassToInject__c = 'DomainProcessInjectionTest.RichmondAccountActionTest',
                IsActive__c = true,
                OrderOfExecution__c = 11.10,
                ProcessContext__c = 'Trigger Execution',
                RelatedDomainBindingSObject__c = 'Account',
                TriggerOperation__c = 'Before Insert',
                Type__c = 'Action'
            )
        };

        DomainProcessCoordinator.domainProcesses.addAll(config);

        List<Account> accList = new List<Account> {
            new Account(Name='Test1', BillingCity='Dallas' ),
            new Account(Name='Test2', BillingCity='Dallas' ),
            new Account(Name='Test3', BillingCity='Richmond'),
            new Account(Name='Test4', BillingCity='Richmond')
        };

        fflib_SObjectDomain.Test.Database.onInsert(accList);
        fflib_SObjectDomain.triggerHandler(DomainProcessInjectionTest.AccountsTestDomainConstructor.class);

        /*List<SObject> result = accounts.getChangedRecords(
				new Set<String>
				{
						'Name',
						'BillingCity',
						'BillingState'
				}
		);*/

        /*List<Account> dallasAcccounts = [select Id, Name, BillingCity, BillingState
                                        from Account
                                        where BillingCity = 'Dallas'
                                        and BillingState = 'Texas'];
        List<Account> richmondAccounts = [select Id, Name, BillingCity, BillingState
                                            from Account
                                            where BillingCity = 'Richmond'
                                            and BillingState = 'Virginia'];*/

        /*for (SObject obj : result) {
            Account acc = (Account) obj;
            if (acc.BillingCity == 'Dallas' && acc.BillingState == 'Texas') {
                System.assert(true, 'Account with city Dallas has state correctly set to Texas');
            }
            else if (acc.BillingCity == 'Richmond' && acc.BillingState == 'Virginia') {
                System.assert(true, 'Account with city Richmond has state correctly set to Virginia');
            }
            else {
                System.assert(false, 'Account not matching any criteria');
            }
        }*/
    }

    private with sharing class AccountsTestDomain 
    extends ApplicationSObjectDomain
    {
        public AccountsTestDomain(List<Account> records)
        {
            super(records);

            // don't enforce CRUD security for Account records
            this.Configuration.disableTriggerCRUDSecurity();
        }
    }

    private class AccountsTestDomainConstructor
            implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain Construct(List<SObject> sObjectList)
        {
            return new AccountsTestDomain(sObjectList);
        }
    }

    private class AccountIsDallasCriteriaTest implements IDomainProcessCriteria
    {   
        private list<Account> records = new list<Account>();

        public IDomainProcessCriteria setRecordsToEvaluate(List<SObject> records)
        {
            this.records.clear();
            this.records.addAll( (list<Account>)records );

            return this;
        }

        public List<SObject> run()
        {
            list<Account> qualifiedRecords = new list<Account>();

            // Loop through the Account records.
            for ( Account record : this.records )
            {
                if ( record.BillingCity.equals('Dallas') )
                {
                    qualifiedRecords.add( record );
                }
            }

            return qualifiedRecords;
        }
    }

    private class AccountIsRichmondCriteriaTest implements IDomainProcessCriteria
    {
        private list<Account> records = new list<Account>();

        public IDomainProcessCriteria setRecordsToEvaluate(List<SObject> records)
        {
            this.records.clear();
            this.records.addAll( (list<Account>)records );

            return this;
        }

        public List<SObject> run()
        {
            list<Account> qualifiedRecords = new list<Account>();

            // Loop through the Account records.
            for ( Account record : this.records )
            {
                if ( record.BillingCity.equals('Richmond') )
                {
                    qualifiedRecords.add( record );
                }
            }

            return qualifiedRecords;
        }
    }

    private class DallasAccountActionTest extends DomainProcessAbstractAction
    {
        public override void runInProcess()
        {
            Account accountRecord = null;

            for ( SObject record : this.records )
            {
                accountRecord = (Account)record;
                accountRecord.BillingState = 'Texas';
            }
        }
    }

    
    private class RichmondAccountActionTest extends DomainProcessAbstractAction
    {
        public override void runInProcess()
        {
            Account accountRecord = null;

            for ( SObject record : this.records )
            {
                accountRecord = (Account)record;
                accountRecord.BillingState = 'Virginia';
            }
        }
    }

}