sfdx-source/core/main/schema/objects/AT4DXMessage__e/AT4DXMessage__e.object-meta.xml
<CustomObject>
    <description>The high volume platform event bus for managing AT4DX messages the org.</description>
    <label>AT4DX Message</label>
    <pluralLabel>AT4DX Messages</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/PlatformEvents_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Maintains the list of Platform-Event consumers.</description>
    <label>Platform Events - Subscription</label>
    <pluralLabel>Platform Events - Subscriptions</pluralLabel>
</CustomObject>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/Consumer__c.field-meta.xml
<CustomField>
    <fullName>Consumer__c</fullName>
    <description>The name of the Apex Class that implements IEventConsumer that the subscription is operating on behalf of.</description>
    <inlineHelpText>The name of the Apex Class that implements IEventConsumer that the subscription is operating on behalf of.</inlineHelpText>
    <label>Consumer</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The name of a specific event that the consumer wants to receive.  Example: &quot;UserCreation&quot;.</description>
    <inlineHelpText>The name of a specific event that the consumer wants to receive.  Example: &quot;UserCreation&quot;.</inlineHelpText>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/EventBus__c.field-meta.xml
<CustomField>
    <fullName>EventBus__c</fullName>
    <description>Specifies the event&apos;s SObject Type that the consumer desires.</description>
    <inlineHelpText>Specifies the event&apos;s SObject Type that the consumer desires.</inlineHelpText>
    <label>Event Bus</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/EventCategory__c.field-meta.xml
<CustomField>
    <fullName>EventCategory__c</fullName>
    <description>Specifies a division for further matching options.  Typically this will be the related SObject name (Example: &quot;Account&quot;, &quot;Intake__c&quot;), but may represent a non-SObject, arbitrary, category (Example: &quot;SalesActivity&quot;)..  This helps to filter subscriptions better.</description>
    <inlineHelpText>Specifies a division for further matching options.  Typically this will be the related SObject name (Example: &quot;Account&quot;, &quot;Intake__c&quot;), but may represent a non-SObject, arbitrary, category (Example: &quot;SalesActivity&quot;)..  This helps to filter subscriptions be</inlineHelpText>
    <label>Event Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/Execute_Synchronous__c.field-meta.xml
<CustomField>
    <fullName>Execute_Synchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Platform Event dynamic subscription will be executed within the same process as the trigger. When unchecked, the subscribed object will be executed as a Queueable.</description>
    <inlineHelpText>When checked, the Platform Event dynamic subscription will be executed within the same process as the trigger. When unchecked, the subscribed object will be executed as a Queueable.</inlineHelpText>
    <label>Execute Synchronous</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/main/schema/objects/PlatformEvents_Subscription__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, then this subscription is active and an event matching this description will be distributed to the consumer specified.</description>
    <inlineHelpText>If checked, then this subscription is active and an event matching this description will be distributed to the consumer specified.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
@IsTest
private class PlatformEventDistributorDIModuleTest {
    @IsTest
    private static void registeredSubscirbersTest()
    {
        PlatformEvents_Subscription__mdt pes1 = new PlatformEvents_Subscription__mdt(
            DeveloperName = 'At4dxUnitTest1',
            Consumer__c = 'PlatformEventDistributorTest.TestPlatformEventsConsumer',
            IsActive__c = true,
            EventCategory__c = Account.getSObjectType().getDescribe().getName(),
            MatcherRule__c = 'MatchEventBusAndCategoryAndEventName',
            EventBus__c = AT4DXMessage__e.SobjectType.getDescribe().getName(),
            Event__c = 'TestOfPlatformEventDistributor',
            Execute_Synchronous__c = true

        );PlatformEvents_Subscription__mdt pes2 = new PlatformEvents_Subscription__mdt(
            DeveloperName = 'At4dxUnitTest2',
            Consumer__c = 'PlatformEventDistributorTest.TestPlatformEventsConsumer',
            IsActive__c = true,
            EventCategory__c = Account.getSObjectType().getDescribe().getName(),
            MatcherRule__c = 'MatchEventBusAndCategoryAndEventName',
            EventBus__c = AT4DXMessage__e.SobjectType.getDescribe().getName(),
            Event__c = 'TestOfPlatformEventDistributor',
            Execute_Synchronous__c = true
        );

        PlatformEventDistributorDIModule dimod = new PlatformEventDistributorDIModule();
        PlatformEventDistributorDIModule.registeredSubscribers = new List<PlatformEvents_Subscription__mdt> { pes1, pes2 };
        dimod.configure();

        System.assertEquals(
            new List<PlatformEvents_Subscription__mdt> { pes1, pes2 },
            PlatformEventDistributorDIModule.registeredSubscribers,
            'Registered Subscirbers Not Equal'
        );

        System.assertEquals(
            null,
            PlatformEventDistributorDIModule.configureWarningMessage,
            'Warning message Not Equal'
        );
    }

    @IsTest
    private static void noEventBusWarningMessageTest(){

        PlatformEvents_Subscription__mdt pes = new PlatformEvents_Subscription__mdt(
            DeveloperName = 'At4dxUnitTest',
            Consumer__c = 'PlatformEventDistributorTest.TestPlatformEventsConsumer',
            IsActive__c = true,
            EventCategory__c = Account.getSObjectType().getDescribe().getName(),
            MatcherRule__c = 'MatchEventBusAndCategoryAndEventName',
            Event__c = 'TestOfPlatformEventDistributor',
            Execute_Synchronous__c = true
        );

        PlatformEventDistributorDIModule dimod = new PlatformEventDistributorDIModule();
        PlatformEventDistributorDIModule.registeredSubscribers = new List<PlatformEvents_Subscription__mdt> { pes };
        dimod.configure();
        
        System.assertEquals(
            'Platform Events - Subscription record named, At4dxUnitTest, does not have required field, Event Bus',
            PlatformEventDistributorDIModule.configureWarningMessage,
            'Warning Message Is Not Equal'
        );
    }

    @IsTest
    private static void noConsumerWarningMessageTest(){

        PlatformEvents_Subscription__mdt pes = new PlatformEvents_Subscription__mdt(
            DeveloperName = 'At4dxUnitTest',
            IsActive__c = true,
            EventCategory__c = Account.getSObjectType().getDescribe().getName(),
            MatcherRule__c = 'MatchEventBusAndCategoryAndEventName',
            EventBus__c = AT4DXMessage__e.SobjectType.getDescribe().getName(),
            Event__c = 'TestOfPlatformEventDistributor',
            Execute_Synchronous__c = true
        );

        PlatformEventDistributorDIModule dimod = new PlatformEventDistributorDIModule();
        PlatformEventDistributorDIModule.registeredSubscribers = new List<PlatformEvents_Subscription__mdt> { pes };
        dimod.configure();
        
        System.assertEquals(
            'Platform Events - Subscription record named, At4dxUnitTest, does not have required field, Consumer',
            PlatformEventDistributorDIModule.configureWarningMessage,
            'Warning Message Is Not Equal'
        );
    }
}